### ISSUE TITLE
JS/Babel/Weback issue when building chart

### ISSUE THREAD

**Issue by devincowan** [OCTRI/REDCap-Vizr#228] opened 2020-10-01 20:26 UTC
I love this tool! Haven't ever had an issue before, but just installed the EM on a diff. Redcap instance v9.9.0 and receive the attached in my console when clicking the "Build a Chart" button
![image](https://user-images.githubusercontent.com/17934193/94859427-beeae980-03f1-11eb-8dfa-9d64509abce8.png)

**Comment by heathharrelson** [comment] 2020-10-01 22:26
Thanks for reporting this issue! The error appears to have occurred in JavaScript provided by REDCap, so there may be some incompatibility with Vizr.

The following in formation would help us determine the cause of the error:

Did anything happen when you clicked the "Build a Chart" button, other than the error in the console?

If you can trigger the error again, please click the line that ends in `bundle.js:459:19532` (see highlighted area in screenshot below).

![annotated-stack](https://user-images.githubusercontent.com/2746306/94869166-9d8dfb80-03f9-11eb-9959-8e4c860afbf4.png)

Clicking that area should open a panel containing the code where the error occurred.  A screenshot of the code displayed would be helpful.

**Comment by devincowan** [comment] 2020-10-01 22:31
@heathharrelson thanks for taking a look. No, nothing else happens when clicking the button. Here's a screenshot
![image](https://user-images.githubusercontent.com/17934193/94869896-7d633a00-0403-11eb-8da7-2f92f8ed6d9f.png)

**Comment by heathharrelson** [comment] 2020-10-01 22:45
It looks like the problem is in the code that is used to show and hide the form used to create charts. Vizr reuses code provided by REDCap to do this, so it's possible that something changed that we need to account for. We'll prioritize reproducing the issue on our end and find a solution. Thanks again for reporting the issue and providing details!

**Comment by heathharrelson** [comment] 2020-10-02 19:00
I looked into this a bit this morning, and the issue is caused by an [unintentional breaking change in jQuery 3.5.0 that impacted many plugins](https://github.com/jquery/jquery/issues/4665), including those provided by Bootstrap. A fix for this issue is noted in the release notes for REDCap 9.9.1:

> Bug fix: Certain menu toggles, such as the "hamburger menu" at the top right of the My Projects page when using a mobile device, were not working correctly due to a breaking change in jQuery 3.5.0 in REDCap 9.9.0 Standard and 9.5.25 LTS. A makeshift patch has been applied to fix this in lieu of a proper fix from jQuery. (Ticket #83490)

I was able to reproduce the issue easily with REDCap 9.9.0, but Vizr does appear to work as expected in 9.9.1. If you control the REDCap instance in question, you can get things working again by upgrading it to REDCap 9.9.1 or greater. Otherwise you will need to alert your REDCap administrators, so they can then upgrade to a version that does not have this defect.

Thanks again for your detailed bug report — they are always appreciated!

**Closed by heathharrelson** 2020-10-02 19:00 UTC
